/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;
import java.net.*;
import java.io.*;

public class App {

    public static void main(String[] args) throws IOException {
        GreetServer server = new GreetServer(5000);
        server.run();
    }
}