/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

public class App {

    public static void main(String[] args) {
        GreetServer server = new GreetServer(5000);
        server.run();
    }
}