/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;
import java.net.*;
import java.io.*;

public class GreetServer implements Runnable {
    private ServerSocket serverSocket;
    private Socket clientSocket;
    private PrintWriter out;
    private BufferedReader in;
    int portNumber;

    public GreetServer(int port){
        this.portNumber = port;
    }

    public void start(int port) throws IOException {
        serverSocket = new ServerSocket(port);
        clientSocket = serverSocket.accept();
        out = new PrintWriter(clientSocket.getOutputStream(), true);
        in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));

        String echoMessage = in.readLine();

        while (echoMessage != null && !echoMessage.equals("close")) {
            out.println("(Echo) " + echoMessage);
            System.out.println("(Echo) " + echoMessage);

            echoMessage = in.readLine();
        }
    }

    public void run() {
        try {
            System.out.println("Starting Server on port " + this.portNumber);
            this.start(this.portNumber);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void stop() throws IOException {
        in.close();
        out.close();
        clientSocket.close();
        serverSocket.close();
    }
}
