/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;
import java.net.*;
import java.util.*;
import java.io.*;

public class GreetServer implements Runnable {
    private ServerSocket serverSocket;
    private Socket clientSocket;
    private PrintWriter out;
    private BufferedReader in;

    int portNumber;
    ArrayList<String> routeList = new ArrayList<>();

    public GreetServer(int port){
        this.portNumber = port;

        routeList.add("/simple_get");
        routeList.add("/simple_get_with_body");
        routeList.add("/head_request");
        routeList.add("/redirect");
        routeList.add("/method_options");
        routeList.add("/method_options2");
        routeList.add("/echo_body");
    }

    public void start(int port) throws IOException {
        serverSocket = new ServerSocket(port);

        while (true){
            try(Socket clientSocket = serverSocket.accept()){
                System.out.println("Client socket " + clientSocket.toString());

                out = new PrintWriter(clientSocket.getOutputStream(), true);
                in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));

                ServerRequest myRequest = new ServerRequest(in);

                System.out.println("\r\n");
                System.out.println("===== Request  =====");
                System.out.println(myRequest.requestLine);
                System.out.println(myRequest.headers);
                System.out.println(myRequest.body);
//
                System.out.println("===== Response =====");

                ServerResponse myResponse = new ServerResponse(myRequest, this.routeList);
//                String returnString = this.returnMessageCreator(requestLines.toString());
                System.out.println(myResponse.response);
//
                out.println(myResponse.response);

            }
        }
    }

    public void run() {
        try {
            System.out.println("Starting Server on port " + this.portNumber);
            this.start(this.portNumber);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void stop() throws IOException {
        in.close();
        out.close();
        clientSocket.close();
        serverSocket.close();
    }

}
