/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertEquals;

public class ServerRequestTest {
    @Test
    public void givenGreetingClient_whenServerResponds_thenStringIsEchoed() {

        String simulatedRequest = "OPTIONS /method_options2 HTTP/1.1\r\n" +
                "Connection: close\r\n" + "Host: 127.0.0.1:5000\r\n" +
                "User-Agent: http.rb/4.3.0\r\n" + "Content-Length: 0\r\n";


    }
}